"""Train the redistribution-aware detector from a leakage-safe CSV manifest."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import torch
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score
from torch import nn
from torch.utils.data import DataLoader
from tqdm import tqdm

from src.augmentations import EvaluationTransform, PairedRobustTransform
from src.data import ImageDataset, PairImageDataset, read_manifest
from src.model import build_model
from src.utils import device_from_arg, set_seed


def loader(dataset, batch_size: int, workers: int, shuffle: bool) -> DataLoader:
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, num_workers=workers,
                      pin_memory=torch.cuda.is_available(), persistent_workers=workers > 0)


@torch.inference_mode()
def validate(model: nn.Module, dataloader: DataLoader, device: torch.device) -> tuple[float, float]:
    model.eval()
    scores, labels = [], []
    for images, targets, _ in dataloader:
        scores.extend(torch.sigmoid(model(images.to(device))).cpu().tolist())
        labels.extend(targets.tolist())
    auc = roc_auc_score(labels, scores)
    accuracy = sum((score >= 0.5) == bool(label) for score, label in zip(scores, labels)) / len(labels)
    return float(auc), float(accuracy)


def load_checkpoint(path: str, device: torch.device) -> dict:
    """Load and validate a checkpoint produced by this training script."""
    checkpoint = torch.load(path, map_location=device, weights_only=False)
    if "model_state" not in checkpoint or "model_config" not in checkpoint:
        raise ValueError(f"{path} is not a compatible detector checkpoint.")
    if checkpoint["model_config"].get("architecture", "convnext_tiny") != "convnext_tiny":
        raise ValueError("This trainer currently supports ConvNeXt-Tiny checkpoints only.")
    return checkpoint


def checkpoint_payload(model: nn.Module, optimizer, scheduler, scaler, epoch: int,
                       best_auc: float, args: argparse.Namespace) -> dict:
    """Capture everything needed to resume after a completed epoch."""
    return {
        "model_state": model.state_dict(),
        "model_config": {"architecture": "convnext_tiny", "use_frequency": not args.spatial_only},
        "optimizer_state": optimizer.state_dict(),
        "scheduler_state": scheduler.state_dict(),
        "scaler_state": scaler.state_dict(),
        "epoch": epoch,
        "planned_epochs": args.epochs,
        "image_size": args.image_size,
        "best_val_auc": best_auc,
        "training_args": vars(args),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Train a robust AIGC image detector.")
    parser.add_argument("--manifest", required=True, help="CSV generated by scripts/build_manifest.py")
    parser.add_argument("--output-dir", default="artifacts/robust_detector")
    parser.add_argument("--epochs", type=int, default=12)
    parser.add_argument("--batch-size", type=int, default=16,
                        help="Use 8 if ConvNeXt-Tiny exhausts GPU memory.")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--image-size", type=int, default=224)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--consistency-weight", type=float, default=0.5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--no-pretrained", action="store_true")
    parser.add_argument("--spatial-only", action="store_true", help="Baseline ablation without the forensic branch.")
    checkpoint_group = parser.add_mutually_exclusive_group()
    checkpoint_group.add_argument(
        "--resume", metavar="LAST_PT",
        help="Resume an interrupted run from last.pt. Keep --epochs equal to the original total.",
    )
    checkpoint_group.add_argument(
        "--init-checkpoint", metavar="CHECKPOINT_PT",
        help="Fine-tune model weights from a prior checkpoint with a fresh optimizer and schedule.",
    )
    args = parser.parse_args()
    if args.epochs < 1 or args.batch_size < 1:
        parser.error("--epochs and --batch-size must be positive")

    set_seed(args.seed)
    device = device_from_arg(args.device)
    loaded_checkpoint = load_checkpoint(args.resume or args.init_checkpoint, device) if (args.resume or args.init_checkpoint) else None
    if loaded_checkpoint is not None:
        checkpoint_uses_frequency = loaded_checkpoint["model_config"]["use_frequency"]
        if args.spatial_only and checkpoint_uses_frequency:
            parser.error("--spatial-only does not match the selected checkpoint. Omit it to retain the checkpoint architecture.")
        # Always reconstruct the architecture stored in the checkpoint.
        args.spatial_only = not checkpoint_uses_frequency
    train_frame, val_frame = read_manifest(args.manifest, "train"), read_manifest(args.manifest, "val")
    train_set = PairImageDataset(train_frame, PairedRobustTransform(args.image_size))
    val_set = ImageDataset(val_frame, EvaluationTransform(args.image_size))
    train_loader = loader(train_set, args.batch_size, args.workers, shuffle=True)
    val_loader = loader(val_set, args.batch_size, args.workers, shuffle=False)
    model = build_model(
        pretrained=not (args.no_pretrained or loaded_checkpoint is not None),
        use_frequency=not args.spatial_only,
    ).to(device)
    if loaded_checkpoint is not None:
        model.load_state_dict(loaded_checkpoint["model_state"])
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)
    scheduler = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr=args.learning_rate,
                                                     epochs=args.epochs, steps_per_epoch=len(train_loader))
    scaler = torch.amp.GradScaler("cuda", enabled=device.type == "cuda")
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    history_path = output_dir / "history.csv"
    best_auc = -1.0
    start_epoch = 1

    if args.resume:
        required = {"optimizer_state", "scheduler_state", "epoch", "planned_epochs"}
        missing = required - set(loaded_checkpoint)
        if missing:
            parser.error(
                f"{args.resume} cannot be resumed because it lacks {sorted(missing)}. "
                "Use --init-checkpoint to fine-tune it instead."
            )
        if loaded_checkpoint["planned_epochs"] != args.epochs:
            parser.error(
                "--resume requires the same --epochs value as the original interrupted run. "
                "Use --init-checkpoint for additional fine-tuning epochs."
            )
        optimizer.load_state_dict(loaded_checkpoint["optimizer_state"])
        scheduler.load_state_dict(loaded_checkpoint["scheduler_state"])
        if "scaler_state" in loaded_checkpoint:
            scaler.load_state_dict(loaded_checkpoint["scaler_state"])
        best_auc = float(loaded_checkpoint.get("best_val_auc", -1.0))
        start_epoch = int(loaded_checkpoint["epoch"]) + 1
        if start_epoch > args.epochs:
            parser.error("This checkpoint has already completed all requested epochs. Use --init-checkpoint to fine-tune further.")
        print(f"Resuming {args.resume} at epoch {start_epoch}/{args.epochs}.")
    elif args.init_checkpoint:
        print(f"Fine-tuning weights from {args.init_checkpoint} with a fresh optimizer and schedule.")

    append_history = bool(args.resume and history_path.exists())
    with open(history_path, "a" if append_history else "w", newline="", encoding="utf-8") as history_file:
        writer = csv.DictWriter(history_file, fieldnames=["epoch", "loss", "val_auc", "val_accuracy"])
        if not append_history:
            writer.writeheader()
        for epoch in range(start_epoch, args.epochs + 1):
            model.train()
            losses = []
            progress = tqdm(train_loader, desc=f"epoch {epoch}/{args.epochs}")
            for clean, damaged, targets in progress:
                clean, damaged, targets = clean.to(device), damaged.to(device), targets.to(device)
                optimizer.zero_grad(set_to_none=True)
                with torch.amp.autocast(device_type=device.type, enabled=device.type == "cuda"):
                    clean_logits = model(clean)
                    damaged_logits = model(damaged)
                    classification = 0.5 * (F.binary_cross_entropy_with_logits(clean_logits, targets) +
                                            F.binary_cross_entropy_with_logits(damaged_logits, targets))
                    consistency = F.mse_loss(torch.sigmoid(clean_logits), torch.sigmoid(damaged_logits))
                    loss = classification + args.consistency_weight * consistency
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)
                scaler.update()
                scheduler.step()
                losses.append(float(loss.detach().cpu()))
                progress.set_postfix(loss=f"{losses[-1]:.4f}")

            val_auc, val_accuracy = validate(model, val_loader, device)
            row = {"epoch": epoch, "loss": sum(losses) / len(losses), "val_auc": val_auc, "val_accuracy": val_accuracy}
            writer.writerow(row)
            history_file.flush()
            print(row)
            if val_auc > best_auc:
                best_auc = val_auc
                payload = checkpoint_payload(model, optimizer, scheduler, scaler, epoch, best_auc, args)
                torch.save(payload, output_dir / "best.pt")
            payload = checkpoint_payload(model, optimizer, scheduler, scaler, epoch, best_auc, args)
            torch.save(payload, output_dir / "last.pt")
    print(f"Best validation ROC-AUC: {best_auc:.4f}; best checkpoint: {output_dir / 'best.pt'}")
    print(f"Latest resumable checkpoint: {output_dir / 'last.pt'}")


if __name__ == "__main__":
    main()
