"""Train the redistribution-aware detector from a leakage-safe CSV manifest."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import torch
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score
from torch import nn
from torch.utils.data import DataLoader
from tqdm import tqdm

from src.augmentations import EvaluationTransform, PairedRobustTransform
from src.data import ImageDataset, PairImageDataset, read_manifest
from src.model import build_model
from src.utils import device_from_arg, set_seed


def loader(dataset, batch_size: int, workers: int, shuffle: bool) -> DataLoader:
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle, num_workers=workers,
                      pin_memory=torch.cuda.is_available(), persistent_workers=workers > 0)


@torch.inference_mode()
def validate(model: nn.Module, dataloader: DataLoader, device: torch.device) -> tuple[float, float]:
    model.eval()
    scores, labels = [], []
    for images, targets, _ in dataloader:
        scores.extend(torch.sigmoid(model(images.to(device))).cpu().tolist())
        labels.extend(targets.tolist())
    auc = roc_auc_score(labels, scores)
    accuracy = sum((score >= 0.5) == bool(label) for score, label in zip(scores, labels)) / len(labels)
    return float(auc), float(accuracy)


def main() -> None:
    parser = argparse.ArgumentParser(description="Train a robust AIGC image detector.")
    parser.add_argument("--manifest", required=True, help="CSV generated by scripts/build_manifest.py")
    parser.add_argument("--output-dir", default="artifacts/robust_detector")
    parser.add_argument("--epochs", type=int, default=12)
    parser.add_argument("--batch-size", type=int, default=16,
                        help="Use 8 if ConvNeXt-Tiny exhausts GPU memory.")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--image-size", type=int, default=224)
    parser.add_argument("--learning-rate", type=float, default=2e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--consistency-weight", type=float, default=0.5)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--no-pretrained", action="store_true")
    parser.add_argument("--spatial-only", action="store_true", help="Baseline ablation without the forensic branch.")
    args = parser.parse_args()
    if args.epochs < 1 or args.batch_size < 1:
        parser.error("--epochs and --batch-size must be positive")

    set_seed(args.seed)
    device = device_from_arg(args.device)
    train_frame, val_frame = read_manifest(args.manifest, "train"), read_manifest(args.manifest, "val")
    train_set = PairImageDataset(train_frame, PairedRobustTransform(args.image_size))
    val_set = ImageDataset(val_frame, EvaluationTransform(args.image_size))
    train_loader = loader(train_set, args.batch_size, args.workers, shuffle=True)
    val_loader = loader(val_set, args.batch_size, args.workers, shuffle=False)
    model = build_model(pretrained=not args.no_pretrained, use_frequency=not args.spatial_only).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)
    scheduler = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr=args.learning_rate,
                                                     epochs=args.epochs, steps_per_epoch=len(train_loader))
    scaler = torch.amp.GradScaler("cuda", enabled=device.type == "cuda")
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    history_path = output_dir / "history.csv"
    best_auc = -1.0

    with open(history_path, "w", newline="", encoding="utf-8") as history_file:
        writer = csv.DictWriter(history_file, fieldnames=["epoch", "loss", "val_auc", "val_accuracy"])
        writer.writeheader()
        for epoch in range(1, args.epochs + 1):
            model.train()
            losses = []
            progress = tqdm(train_loader, desc=f"epoch {epoch}/{args.epochs}")
            for clean, damaged, targets in progress:
                clean, damaged, targets = clean.to(device), damaged.to(device), targets.to(device)
                optimizer.zero_grad(set_to_none=True)
                with torch.amp.autocast(device_type=device.type, enabled=device.type == "cuda"):
                    clean_logits = model(clean)
                    damaged_logits = model(damaged)
                    classification = 0.5 * (F.binary_cross_entropy_with_logits(clean_logits, targets) +
                                            F.binary_cross_entropy_with_logits(damaged_logits, targets))
                    consistency = F.mse_loss(torch.sigmoid(clean_logits), torch.sigmoid(damaged_logits))
                    loss = classification + args.consistency_weight * consistency
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)
                scaler.update()
                scheduler.step()
                losses.append(float(loss.detach().cpu()))
                progress.set_postfix(loss=f"{losses[-1]:.4f}")

            val_auc, val_accuracy = validate(model, val_loader, device)
            row = {"epoch": epoch, "loss": sum(losses) / len(losses), "val_auc": val_auc, "val_accuracy": val_accuracy}
            writer.writerow(row)
            history_file.flush()
            print(row)
            if val_auc > best_auc:
                best_auc = val_auc
                torch.save({
                    "model_state": model.state_dict(),
                    "model_config": {"architecture": "convnext_tiny", "use_frequency": not args.spatial_only},
                    "image_size": args.image_size,
                    "best_val_auc": best_auc,
                    "training_args": vars(args),
                }, output_dir / "best.pt")
    print(f"Best validation ROC-AUC: {best_auc:.4f}; checkpoint: {output_dir / 'best.pt'}")


if __name__ == "__main__":
    main()
